compressionLevel: mixed

enableGlobalCache: false

npmPublishRegistry: "https://npm.pkg.github.com"

npmScopes:
  term-finance:
    npmAlwaysAuth: true
    npmAuthToken: "${NODE_AUTH_TOKEN:-}"
    npmRegistryServer: "https://npm.pkg.github.com"
