checksumBehavior: update

nodeLinker: node-modules

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

yarnPath: .yarn/releases/yarn-3.2.0.cjs

npmPublishRegistry: "https://npm.pkg.github.com"
npmRegistries:
  "https://npm.pkg.github.com":
    npmAlwaysAuth: true
    npmAuthToken: '${NODE_AUTH_TOKEN:-}'
npmScopes:
  "term-finance":
    npmRegistryServer: "https://npm.pkg.github.com"
    npmAlwaysAuth: true
    npmAuthToken: '${NODE_AUTH_TOKEN:-}'
