name: CI
on: [push]
permissions:
  contents: read
  pages: write
  id-token: write
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 0
      - run: corepack enable
      - uses: actions/setup-node@v3
        with:
          node-version: "18.15"
          cache: yarn
      - run: yarn install  --immutable
      - run: yarn build
      - run: yarn check:coverage
        env:
          REPORT_GAS: "true"
      - uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
